config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:show, :edit, :update, :index]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]


  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have creatad book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice]="Book was successfully destroyed."
      redirect_to books_path
    end
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<%= form_with model: book, local:true do |f| %>
 <div class="form-group">
  <label for="book_title">Title</label></br>
  <%= f.text_field :title,class: "form-control book_title" %>
 </div>
 <div class="form-group">
  <label for="book_opinion">Opinion</label></br>
  <%= f.text_area :body,class: "form-control book_body" %>
 </div>
 <div class="form-group">
  <%= f.submit "Create Book", class: "btn btn-success" %>
 </div>

<% end %>

app/views/books/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <div class="error_explanation">
          <% if @book.errors.any? %>
            <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
            <% @book.errors.full_messages.each do |message| %>
              <ul>
                <li><%= message %></li>
              </ul>
            <% end %>
          <% end %>          
        </div>

        <%= form_with model: @book, local:true do |f| %>
         <div class="form-group">
          <label for="book_title">Title</label></br>
          <%= f.text_field :title,class: "form-control book_title" %>   
         </div>
         <div class="form-group">
          <label for="book_opinion">Opinion</label></br>
          <%= f.text_area :body,class: "form-control book_body" %></br>
          <%= f.submit 'Update Book' %>
         </div>

        <% end %>
        <%= link_to "Show", book_path(@book) %>
        |
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
    <div class="container px-5 px-sm-0">
      <div class="error_explanation">
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
        <% @book.errors.full_messages.each do |message| %>
          <ul>
            <li><%= message %></li>
          </ul>
        <% end %>
      <% end %>
      </div>
      <div class="row">



        <div class="col-md-3">
         <%= render 'users/user', user: @user %>
         <h2 class="mt-3">New book</h2>
         <%= render 'books/book', book: @book %>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
                <tr>
                  <td>
                    <%= link_to user_path(book.user) do %>
                      <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg", size:'40x40' %>
                    <% end %>
                  </td>
                  <td><%= link_to book.title, book_path(book.id) %></td>
                  <td><%= book.body %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
         </div>
      </div>
    </div>
</main>

app/views/books/show.html.erb
<main>
<div class="container">
  <div class="row">
   <div class="col-md-3">
    <%= render 'users/user', user: @user %>
    <h2>New book</h2>
    <%= render 'books/book', book: @newbook %>
   </div>
   <div class="col-md-8 offset-md-1">
   　<h2>Book detail</h2>
   　<table class="table">
   　  <tbody>
   　   <tr>
   　    <td><%= attachment_image_tag @user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %><br><%= link_to @user.name, user_path(@user) %></td>
   　    <td></td>
   　    <td><%= link_to @book.title,book_path(@book) %></td>
   　    <td><%= @book.body %></td>
   　    <% if @user.id == current_user.id %>
   　     <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success"%></td>
   　     <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %></td>
   　    <% end %>
   　   </tr>
   　  </tbody>
   　</table>
   </div>

  </div>
</div>
</main>